"""Controlled S3 object keys.

The original filename is reduced to a single path segment. The document id
is generated by the server. User input never becomes a directory prefix.
"""

import re

_ALLOWED = re.compile(r"[^A-Za-z0-9._-]")


class UnsafeFilenameError(Exception):
    """The client filename cannot be stored safely."""


def sanitize_filename(filename: str | None) -> str:
    """Return a single safe path segment or raise ``UnsafeFilenameError``."""
    if filename is None:
        raise UnsafeFilenameError
    segment = filename.replace("\\", "/").split("/")[-1].strip()
    segment = _ALLOWED.sub("_", segment)
    segment = segment.strip("._")
    if not segment or segment in {".", ".."} or ".." in segment:
        raise UnsafeFilenameError
    return segment[:120]


def build_object_key(document_id: str, filename: str | None) -> tuple[str, str]:
    """Return ``(object_key, safe_filename)``."""
    if not document_id or "/" in document_id or ".." in document_id:
        raise UnsafeFilenameError
    safe_filename = sanitize_filename(filename)
    return f"documents/{document_id}/{safe_filename}", safe_filename
